development:
  cloud_name: minikus
  api_key: '874837483274837'
  api_secret: a676b67565c6767a6767d6767f676fe1
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: minikus
  api_key: '874837483274837'
  api_secret: a676b67565c6767a6767d6767f676fe1
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: minikus
  api_key: '874837483274837'
  api_secret: a676b67565c6767a6767d6767f676fe1
  enhance_image_tag: true
  static_image_support: false
