development:
  cloud_name: minikus
  api_key: '241279335228834'
  api_secret: Jbrg5kE_hKjew5hfSj9B-yxpCQU
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: minikus
  api_key: '241279335228834'
  api_secret: Jbrg5kE_hKjew5hfSj9B-yxpCQU
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: minikus
  api_key: '241279335228834'
  api_secret: Jbrg5kE_hKjew5hfSj9B-yxpCQU
  enhance_image_tag: true
  static_image_support: false
