# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ee8100bad24296e343a01fa5781b689c2e09acc31171d61ec41a6b9414e47f4b9c8cb55cafb4c3ae27fdd60db15a8f93199420932046672fd18e9edc9410490

test:
  secret_key_base: e6db73ca692806d9466639d03504871c656477c73b024217ec19fbeae689490ae140fe25bcb423245a48b87e2740d77fc2996dd47e307a85712897bd158922b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
